In [1]:
!pip install numpy

In [2]:
import numpy as np

In [4]:
lst = [1,2,3,4]
arr = np.array(lst)

In [5]:
arr

array([1, 2, 3, 4])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.shape

(4,)

In [10]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [12]:
arr1.shape

(2, 3)

In [13]:
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
arr1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [15]:
arr1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [16]:
arr1.dtype

dtype('int32')

In [18]:
np.arange(0,20,2).reshape(2,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [22]:
np.arange(0,20,2).reshape(5,2).shape

(5, 2)

In [23]:
range(0,20,2)

range(0, 20, 2)

In [24]:
list(range(0,20,2))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [25]:
np.array(range(0,20,2))

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
np.arange(50, 1, -2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [38]:
np.linspace(1, 20, 40)

array([ 1.        ,  1.48717949,  1.97435897,  2.46153846,  2.94871795,
        3.43589744,  3.92307692,  4.41025641,  4.8974359 ,  5.38461538,
        5.87179487,  6.35897436,  6.84615385,  7.33333333,  7.82051282,
        8.30769231,  8.79487179,  9.28205128,  9.76923077, 10.25641026,
       10.74358974, 11.23076923, 11.71794872, 12.20512821, 12.69230769,
       13.17948718, 13.66666667, 14.15384615, 14.64102564, 15.12820513,
       15.61538462, 16.1025641 , 16.58974359, 17.07692308, 17.56410256,
       18.05128205, 18.53846154, 19.02564103, 19.51282051, 20.        ])

In [37]:
np.linspace(1, 20, 40, retstep=True)

(array([ 1.        ,  1.48717949,  1.97435897,  2.46153846,  2.94871795,
         3.43589744,  3.92307692,  4.41025641,  4.8974359 ,  5.38461538,
         5.87179487,  6.35897436,  6.84615385,  7.33333333,  7.82051282,
         8.30769231,  8.79487179,  9.28205128,  9.76923077, 10.25641026,
        10.74358974, 11.23076923, 11.71794872, 12.20512821, 12.69230769,
        13.17948718, 13.66666667, 14.15384615, 14.64102564, 15.12820513,
        15.61538462, 16.1025641 , 16.58974359, 17.07692308, 17.56410256,
        18.05128205, 18.53846154, 19.02564103, 19.51282051, 20.        ]),
 0.48717948717948717)

In [45]:
np.linspace(1,20,40).reshape(10,4)

array([[ 1.        ,  1.48717949,  1.97435897,  2.46153846],
       [ 2.94871795,  3.43589744,  3.92307692,  4.41025641],
       [ 4.8974359 ,  5.38461538,  5.87179487,  6.35897436],
       [ 6.84615385,  7.33333333,  7.82051282,  8.30769231],
       [ 8.79487179,  9.28205128,  9.76923077, 10.25641026],
       [10.74358974, 11.23076923, 11.71794872, 12.20512821],
       [12.69230769, 13.17948718, 13.66666667, 14.15384615],
       [14.64102564, 15.12820513, 15.61538462, 16.1025641 ],
       [16.58974359, 17.07692308, 17.56410256, 18.05128205],
       [18.53846154, 19.02564103, 19.51282051, 20.        ]])

In [47]:
np.zeros(3)

array([0., 0., 0.])

In [48]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [50]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [52]:
np.ones((3,2), dtype = int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [54]:
np.ones((3,3, 6))

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [61]:
5 + np.ones((3,2,5)).reshape(2,15)

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.]])

In [62]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [69]:
np.eye(3, k = 1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [75]:
np.eye(6).reshape(12, 3)

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

In [76]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [77]:
print("Random number generation(Uniform distribution)")

np.random.rand(2,3)

Random number generation(Uniform distribution)


array([[0.13924699, 0.25909779, 0.83724286],
       [0.27753433, 0.75684467, 0.8755938 ]])

In [79]:
np.random.randint(1, 100, 10)

array([66, 22, 82, 26, 34,  4, 95,  8, 64, 14])

In [85]:
np.random.randint(5, size=5)

array([2, 2, 4, 3, 0])

In [86]:
np.random.randint(1, 100, (4,4))

array([[21, 61, 62, 62],
       [ 5, 14, 84, 51],
       [76, 59, 13, 25],
       [ 2, 56, 34,  8]])

In [87]:
arr = np.arange(0,11)

In [88]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [93]:
arr[-1:7:-1]

array([10,  9,  8])

In [94]:
arr[-1:3:-2]

array([10,  8,  6,  4])

In [97]:
arr1 = np.random.randint(2,100,20).reshape(5,4)

In [98]:
arr1

array([[27, 33, 58, 31],
       [ 8, 25, 48, 41],
       [81, 45, 13, 83],
       [10, 18, 41, 51],
       [41, 91, 23, 96]])

In [99]:
arr1[0:3, 0:3]

array([[27, 33, 58],
       [ 8, 25, 48],
       [81, 45, 13]])

In [102]:
arr1[3:5, 1:4]

array([[18, 41, 51],
       [91, 23, 96]])

In [103]:
arr1[2:4, 1:3]

array([[45, 13],
       [18, 41]])

In [104]:
arr1

array([[27, 33, 58, 31],
       [ 8, 25, 48, 41],
       [81, 45, 13, 83],
       [10, 18, 41, 51],
       [41, 91, 23, 96]])

In [106]:
arr1[0:2,0:1]

array([[27],
       [ 8]])

In [108]:
arr1[0:2, 3:5]

array([[31],
       [41]])

In [126]:
##Universal functions

arr1 = np.random.randint(1,100,(3,3))
arr2 = np.random.randint(20,100,(3,3))

In [112]:
arr1

array([[86, 82, 75],
       [40,  1, 15],
       [16, 56, 68]])

In [113]:
arr2

array([[81, 65, 88],
       [44, 31, 81],
       [67, 36, 81]])

In [114]:
arr1 * arr2

array([[6966, 5330, 6600],
       [1760,   31, 1215],
       [1072, 2016, 5508]])

In [115]:
arr1 + arr2

array([[167, 147, 163],
       [ 84,  32,  96],
       [ 83,  92, 149]])

In [116]:
arr1 / arr2

array([[1.0617284 , 1.26153846, 0.85227273],
       [0.90909091, 0.03225806, 0.18518519],
       [0.23880597, 1.55555556, 0.83950617]])

In [117]:
np.sqrt(arr1)

array([[9.2736185 , 9.05538514, 8.66025404],
       [6.32455532, 1.        , 3.87298335],
       [4.        , 7.48331477, 8.24621125]])

In [118]:
np.exp(arr1)

array([[2.23524660e+37, 4.09399696e+35, 3.73324200e+32],
       [2.35385267e+17, 2.71828183e+00, 3.26901737e+06],
       [8.88611052e+06, 2.09165950e+24, 3.40427605e+29]])

In [119]:
np.log10(arr1)

array([[1.93449845, 1.91381385, 1.87506126],
       [1.60205999, 0.        , 1.17609126],
       [1.20411998, 1.74818803, 1.83250891]])

In [120]:
arr1 = np.arange(1,10)

In [121]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
arr1[4] = 2000

In [123]:
arr1

array([   1,    2,    3,    4, 2000,    6,    7,    8,    9])

In [124]:
np.dot([[1,2,3],[4,5,6]], [[7,8],[9,10],[11,12]]) # matrix multiplication

array([[ 58,  64],
       [139, 154]])

In [127]:
np.dot(arr1, arr2)

array([[18088, 12022, 18843],
       [11411,  6788, 10645],
       [10428,  6360, 10524]])

In [128]:
np.matmul(arr1, arr2) # matrix multiplication same function but diffrent name

array([[18088, 12022, 18843],
       [11411,  6788, 10645],
       [10428,  6360, 10524]])